// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH_kREPTQyy-YOslbkuHh_FlBDCyqalho',
    appId: '1:241665118590:web:0950a79a11c6d02825632f',
    messagingSenderId: '241665118590',
    projectId: 'trouble-sarthi',
    authDomain: 'trouble-sarthi.firebaseapp.com',
    databaseURL: 'https://trouble-sarthi-default-rtdb.firebaseio.com',
    storageBucket: 'trouble-sarthi.firebasestorage.app',
    measurementId: 'G-PZCZ7BJEZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbt0_NpzghXo7lO-AD1oAV7_FnfOPvCUw',
    appId: '1:241665118590:android:68c74407e229588225632f',
    messagingSenderId: '241665118590',
    projectId: 'trouble-sarthi',
    databaseURL: 'https://trouble-sarthi-default-rtdb.firebaseio.com',
    storageBucket: 'trouble-sarthi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN_OXztXdybB0c7J8tY7-Pdl-fNUm9YwQ',
    appId: '1:241665118590:ios:04b55adbf0ebac0f25632f',
    messagingSenderId: '241665118590',
    projectId: 'trouble-sarthi',
    databaseURL: 'https://trouble-sarthi-default-rtdb.firebaseio.com',
    storageBucket: 'trouble-sarthi.firebasestorage.app',
    androidClientId: '241665118590-j2q0gbubupqigouts9cej9n53t11fpsa.apps.googleusercontent.com',
    iosClientId: '241665118590-nq45kvvhr9e0p88fuchevgilgff4uv2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.sarthiKendra',
  );
}
